local UEHelpers = require("UEHelpers")
local commands = require("libs/commands")
local logic = require("libs/logic")
local logMgr = FindFirstOf("BP_PalLogManager_C")
RegisterHook("/Script/Pal.PalPlayerController:DamageReactionComponent_ProcessDamage_ToServer_ToSelfPlayer", logic.damageHook)
RegisterHook("/Script/Pal.PalStatusComponent:AddStatus_ToServer", logic.statusHook)
RegisterHook("/Script/Pal.PalPlayerState:EnterChat_Receive", logic.chatHook)